### ISSUE TITLE
Problème édition compétences

### ISSUE THREAD

**Issue by rootkit7628** [iTeam-S/Gestion-Portfolio#2]
Quand j'ai voulu éditer mes compétences ça ne marche pas et ça me retourne une erreur dans la console 
```
Erreurs sur la mise à jours des données dans la table 'competences' ...!<br>:SQLSTATE[HY093]: Invalid parameter number: parameter was not defined
```
![image](https://user-images.githubusercontent.com/60097202/149205455-d5845d25-60a7-499f-afe8-0ac8eeae74a2.png)

De plus, je propose de mettre un peu plus de message d'erreur pour les utilisateurs quand il y a des problèmes de requêtes

**Comment by lahatra3** [comment]
Merci beaucoup !!!

**Comment by lahatra3** [comment]
Merci beaucoup, je vais le corriger !!!

**Comment by gaetan1903** [comment]
@rootkit7628 certaines de mes compétences ont disparu.  c'est peut-être lié ?

**Comment by gaetan1903** [comment]
c'est lié à mon issu #3

**Comment by gaetan1903** [comment]
je pense que le problème n'est plus d'actualité
