### ISSUE TITLE
Impossible de modifier

### ISSUE THREAD

**Issue by gaetan1903** [iTeam-S/Gestion-Portfolio#4]
Hello, 

![image](https://user-images.githubusercontent.com/43904633/161377284-2f856b5e-f3ce-421d-87ac-bc9808d0f458.png)

J'ai changer dark de 1 en 0, et il me semble que le bouton ENREGISTRER n'est toujours pas activé

**Comment by lahatra3** [comment]
ça devra marcher maintenant...

**Comment by gaetan1903** [comment]
toujours KO 

https://user-images.githubusercontent.com/43904633/161444024-a963c204-a1a8-4811-848a-f9e1e738ca03.mp4

**Comment by lahatra3** [comment]
c'était le regex de mail que j'ai écrit qui n'a pas été performant, mais le problème est réglé... Merci Monsieur !

**Comment by gaetan1903** [comment]
On clos, merci 

ça marche maintenant
