### ISSUE TITLE
Partie supprimé dans mes inputs

### ISSUE THREAD

**Issue by gaetan1903** [iTeam-S/Gestion-Portfolio#5]
![image](https://user-images.githubusercontent.com/43904633/161448889-831fe438-f917-4f36-b837-baf7c3adb0eb.png)
 
Normalement, misy <br> io mitsy ny texte amn'description an'ilay experience ako, 

de quand je met à jour, de miala doly ilay <br>, nefa j'ai besoin pour mettre à la ligne, ary anaty portfolio ko, 

sinon lasa otrzao 
![image](https://user-images.githubusercontent.com/43904633/161448937-7b45cc2e-b501-48f3-bae0-0e36e6588963.png)

au lieu de comme ça 
![image](https://user-images.githubusercontent.com/43904633/161448955-140a9d13-ba76-48de-9631-51fb1463daf4.png)

**Comment by lahatra3** [comment]
c'est l'api qui enleve toutes les balises...!

**Comment by gaetan1903** [comment]
c'est deja OK ?
